name: Cache Demo

on: [push]  # Runs on every push to any branch

jobs:
  demo:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: prime-cache-23556f4  # Exact step name required
      id: cache-step
      uses: actions/cache@v4
      with:
        path: ~/.cache/demo  # Caches a dummy folder
        key: cache-23556f4   # Exact key required
        
    - name: Show cache result
      run: echo "Cache result: ${{ steps.cache-step.outputs.cache-hit }}"
